-- Perf audit 2026-08-03 regression fix: the immediately-preceding migration
-- (20260803193354_add_stage_history_report_index) was generated by `prisma migrate dev`,
-- which diffs the ENTIRE database against the ENTIRE schema.prisma file — not just the model
-- being changed. Because these two pg_trgm indexes are deliberately NOT declared in
-- schema.prisma (see 20260803185528_add_pg_trgm_candidate_search_indexes for why), that diff
-- proposed DROPping them as "drift", and migrate dev auto-applied the drop. This migration
-- recreates them.
--
-- IMPORTANT for future schema changes: as long as these two indexes stay undeclared in
-- schema.prisma, ANY future `prisma migrate dev` run will try to drop them again. From now on,
-- always run `prisma migrate dev --create-only` first and inspect the generated SQL for
-- unexpected `DROP INDEX` statements referencing candidates_name_trgm_idx /
-- candidates_email_trgm_idx before applying.

CREATE INDEX IF NOT EXISTS "candidates_name_trgm_idx" ON "candidates" USING GIN ("name" gin_trgm_ops);

CREATE INDEX IF NOT EXISTS "candidates_email_trgm_idx" ON "candidates" USING GIN ("email" gin_trgm_ops);
